# Generated by Django 4.0.2 on 2022-02-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='novoBody',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
