# Generated by Django 4.0.2 on 2022-02-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_novobody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='novoBody',
        ),
    ]
